import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar/Sidebar";

import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";

const poppins = Poppins({ weight: "300", subsets: ["devanagari"] });

export const metadata: Metadata = {
  title: "GameHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <main className="flex bg-primary">
          <Sidebar />
          <div className="min-h-[calc(100vh-5rem)] mt-20 w-full">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
